### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by seth57rules** [kgeeknerdsley/Disneyland-Simulator#2]
NOTHING WORKS GAVIN!
![technical_derpyculties_vector_by_inkwell_pony-d4rpq7d](https://cloud.githubusercontent.com/assets/8302046/6633222/74fdb42c-c902-11e4-98be-0d3e176f1924.png)

**Comment by kgeeknerdsley** [comment]
DISNEYLAND IS CLOSE
